### ISSUE TITLE
⏰ No Data Alerting - Rate Metrics

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/staff-device-dns-dhcp-admin#488]
## User Story

As a… cloud ops engineer
I need/want/expect to… be alerted when the rate metrics in [this](https://monitoring-alerting.staff.service.justice.gov.uk/d/cEwjsH1Gk/kea-dhcp-metrics?orgId=1&refresh=1m) dashboard have no data. 
So that… I am aware of issues relating to the rate metrics not being picked up. 

## Value / Purpose
Post an incident we noted that these metrics were no data and we had not been alerted. This is not acceptable and this ticket should resolve this. 

## Definition of Done (DoD)
Alerts are triggered when the following metrics provide no data. 
![image](https://user-images.githubusercontent.com/26419401/165053231-7fe55de8-970c-49df-998e-9ad21cef11c3.png)

**Comment by Gary-H9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/staff-device-dns-dhcp-admin/488?planning-poker) with ZenHub @ASTRobinson @bagg3rs @kyphutruong @mitchdawson1982 @moontune @mTouhid @wanieldilson

**Comment by wanieldilson** [comment]
https://stackoverflow.com/questions/62122516/alerting-missing-metric-for-many-hosts-in-alertmanager

This looks promising :up
