### ISSUE TITLE
⬆️ DNS DHCP Admin Portal MySQL Upgrade Issue.

### ISSUE THREAD

**Issue by ASTRobinson** [ministryofjustice/staff-device-dns-dhcp-admin#500]
### User Story

As a… Cloud Ops Engineer
I want to… ensure MySQL dependency upgrades are successfully tested locally before being pushed through the pipeline.
So that… i can be confident that no downtime will arise from such upgrades.

### Value / Purpose

The purpose of this ticket is to review testing & documentation for Dependabot (MySQL) upgrades. The following PR ([499](https://github.com/ministryofjustice/staff-device-dns-dhcp-admin/pull/499)) [](url) passed all local development testing but failed to deploy successfully to Dev / Pre-Prod through the pipeline.

There are any...
 - Additional tests that could be written 
 - Database upgrade documentation 

### Useful Contacts

Aaron Robinson (Cloud Ops Team) 

### Additional Information

https://github.com/ministryofjustice/staff-device-dns-dhcp-admin/pull/499

https://sentry.io/organizations/ministryofjustice/issues/3247582520/?project=5458370&referrer=slack

### Definition of Done

- [ ] Documentation has been written / updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by mitchdawson1982** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/staff-device-dns-dhcp-admin/500?planning-poker) with ZenHub @Gary-H9 @ASTRobinson @wanieldilson @mTouhid @kyphutruong @emileswarts @moontune @bagg3rs

**Comment by mitchdawson1982** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/staff-device-dns-dhcp-admin/500?planning-poker) with ZenHub @bagg3rs @moontune

**Comment by mTouhid** [comment]
Make sure documentation is there to alert engineers that updating local db container and gems should also trigger an upgrade on the RDS
