### ISSUE TITLE
❌ Create  appropriate government design system pages for errors (404/500)

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/staff-device-dns-dhcp-admin#530]
### User Story

As a… User of the Portal
I need/want/expect to… see a branded 404 page when I navigate to an incorrect url
So that…

**Comment by mitchdawson1982** [comment]
Replace the default ruby error page(s) and replace with Government design system variants.
Examples:
https://design-system.service.gov.uk/patterns/page-not-found-pages/

**Comment by Gary-H9** [comment]
Created a [branch](https://github.com/ministryofjustice/staff-device-dns-dhcp-admin/tree/add-custom-404-page) for this piece of work, further investigation needs to be performed on the routing.
