### ISSUE TITLE
⚠️ Set Rate Limit on Sentry.io

### ISSUE THREAD

**Issue by ASTRobinson** [ministryofjustice/staff-device-dns-dhcp-admin#547]
### User Story

As a Sentry.io user 
I want to limit the rate of errors reported to sentry.io
So that we as a team do not use up the transaction quota for MoJ

### Value / Purpose

[Sentry.io](http://sentry.io/) is a shared service across many projects and due to one team not having configured rate limiting a single project has used up the monthly error transaction quota (about 90% in a single day). - let's not be that team. 

### Useful Contacts

Aaron Robinson

### Additional Information

original slack message: https://mojdt.slack.com/archives/C02D2NEF9CJ/p1657787053509449

Sentry.io [rate limiting](https://docs.sentry.io/product/accounts/quotas/manage-event-stream-guide/#6-rate-limiting) 

Cloud Platform [guidance](https://operations-engineering.service.justice.gov.uk/documentation/services/sentry.html#sentry-io).

### Definition of Done

Rate limiting correctly configured on Sentry.io for our projects:

- [x]  staff-device-dns-dhcp-admin
- [x]  staff-device-dhcp-metrics-agent
- [x]  staff-device-dns-metrics-agent

**Comment by satishgummadellimoj** [comment]
![image.png](https://images.zenhubusercontent.com/646dd83dcd41064b3c78f654/227b9055-ef2d-43b6-b92c-40d009b7cbab)  staff-device-dhcp-metrics-agent with rate limit

**Comment by satishgummadellimoj** [comment]
![image.png](https://images.zenhubusercontent.com/646dd83dcd41064b3c78f654/33c69586-51f7-46c5-b4ae-5a89a882fd52) staff-device-dns-dhcp-admin with rate limit

**Comment by satishgummadellimoj** [comment]
![image.png](https://images.zenhubusercontent.com/646dd83dcd41064b3c78f654/5c32bf15-7544-4269-8f67-2764471df7ca) staff-device-dns-metrics-agent with rate limit
