### ISSUE TITLE
DHCP Scopes for Newbold Revel

### ISSUE THREAD

**Issue by mTouhid** [ministryofjustice/staff-device-dns-dhcp-admin#573]
Based on the request received from Tariq Mahmood and from the attached doc [https://app.zenhub.com/files/285252478/59f6c3ec-3bd6-4730-9a14-c4c73ae61427/download](https://app.zenhub.com/files/285252478/59f6c3ec-3bd6-4730-9a14-c4c73ae61427/download), following scopes are required for Newbold Revel site:

- [ ] 10.150.200.0/22
- [ ] 10.150.204.0/22

**Comment by 443635** [comment]
Hi Touhid
Yes I can confirm the subnets provided by Vodafone are correct. please drop me a message once its done. I will keep an eye here too.

**Comment by mTouhid** [comment]
Subnets have been created:
![image.png](https://images.zenhubusercontent.com/622a0aacce2003aab867cfcb/8b2bfe2a-bb10-4a15-a00a-69997326acce) 
![image.png](https://images.zenhubusercontent.com/622a0aacce2003aab867cfcb/f09b6dec-505f-4e4d-ab4f-f8807354333e)

**Comment by TariqMahmood4** [comment]
Thank you so much Touhid for your help.
