### ISSUE TITLE
DHCP Option 234 - Inform responses being dropped.

### ISSUE THREAD

**Issue by mitchdawson1982** [ministryofjustice/staff-device-dns-dhcp-admin#609]
**** This ticket serves for information purposes only. ****

The devops team were approached by the EUC team with regards to issues with clients obtaining dhcp option 234. After some testing it became apparent that windows clients first obtained an ip address via a normal discover, offer, request, ack (DORA) flow, however sometime afterwards the client would request parameter 234 via a dhcp inform message. The difference with inform messages is that the response from the dhcp server is sent back directly to the client rather than via the dhcp relay ip. It was suspected that responses from the server were being dropped somewhere as the client never received it. After testing and validating the policies and logs in the 10sc model office environment it was found that there were no firewall rules permitting responses from the dhcp server subnets back to client subnets and the responses were therefore being denied.

**Comment by Gary-H9** [comment]
RITM1157628 covers this piece of work from a network perspective.
