### ISSUE TITLE
Create a pipeline to deploy branch builds to Development environment

### ISSUE THREAD

**Issue by satishgummadellimoj** [ministryofjustice/staff-device-dns-dhcp-admin#713]
- Create a deploy branch through which the pipeline will be created
- Pipeline should only have build, test and deploy to Development stages

**Comment by tomwells98** [comment]
Ticket needs to be refined again - how do we want to approach? e.g. should this be changes into an epic.

**Comment by tomwells98** [comment]
Ticket needs to be refined again - how do we want to approach? e.g. should this be changes into an epic.
